### ISSUE TITLE
Broken / Wrong certificat on https://storaged.org

### ISSUE THREAD

**Issue by fabiscafe** [storaged-project/storaged-project.github.io#7]
[storaged-project.github.io](https://github.com/storaged-project/storaged-project.github.io) redirects to http://storaged.org, depending on the browser, this however ends up on https:// and this fails, because the "*.github.com" cert is used.

There should be an own cert set for [http://storaged.org](http://storaged.org), so https will work, even of only for redirection purposes.

**Comment by vojtechtrefny** [comment]
The certificate should now be correctly set for https://storaged.org.
